// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type DeadLetterTask struct {
	ID              pgtype.UUID        `json:"id"`
	TaskExecutionID pgtype.UUID        `json:"task_execution_id"`
	LastError       pgtype.Text        `json:"last_error"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type TaskAttempt struct {
	ID              pgtype.UUID        `json:"id"`
	TaskExecutionID pgtype.UUID        `json:"task_execution_id"`
	WorkerID        string             `json:"worker_id"`
	Attempt         int32              `json:"attempt"`
	Status          string             `json:"status"`
	ErrorMessage    pgtype.Text        `json:"error_message"`
	StartedAt       pgtype.Timestamptz `json:"started_at"`
	CompletedAt     pgtype.Timestamptz `json:"completed_at"`
}

type TaskExecution struct {
	ID                  pgtype.UUID        `json:"id"`
	WorkflowExecutionID pgtype.UUID        `json:"workflow_execution_id"`
	WorkflowTaskID      pgtype.UUID        `json:"workflow_task_id"`
	Status              string             `json:"status"`
	WorkerID            pgtype.Text        `json:"worker_id"`
	Attempt             int32              `json:"attempt"`
	LeaseExpiresAt      pgtype.Timestamptz `json:"lease_expires_at"`
	StartedAt           pgtype.Timestamptz `json:"started_at"`
	CompletedAt         pgtype.Timestamptz `json:"completed_at"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	NextRetryAt         pgtype.Timestamptz `json:"next_retry_at"`
	MaxAttempts         int32              `json:"max_attempts"`
}

type Tenant struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Worker struct {
	ID                 string             `json:"id"`
	Hostname           string             `json:"hostname"`
	Version            pgtype.Text        `json:"version"`
	MaxConcurrentTasks int32              `json:"max_concurrent_tasks"`
	ActiveTasks        int32              `json:"active_tasks"`
	SupportedTaskTypes []byte             `json:"supported_task_types"`
	LastHeartbeat      pgtype.Timestamptz `json:"last_heartbeat"`
	Status             string             `json:"status"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type Workflow struct {
	ID         pgtype.UUID        `json:"id"`
	TenantID   pgtype.UUID        `json:"tenant_id"`
	Name       string             `json:"name"`
	Definition []byte             `json:"definition"`
	Version    int32              `json:"version"`
	Status     string             `json:"status"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type WorkflowExecution struct {
	ID             pgtype.UUID        `json:"id"`
	TenantID       pgtype.UUID        `json:"tenant_id"`
	WorkflowID     pgtype.UUID        `json:"workflow_id"`
	IdempotencyKey pgtype.Text        `json:"idempotency_key"`
	Status         string             `json:"status"`
	StartedAt      pgtype.Timestamptz `json:"started_at"`
	CompletedAt    pgtype.Timestamptz `json:"completed_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type WorkflowTask struct {
	ID           pgtype.UUID `json:"id"`
	WorkflowID   pgtype.UUID `json:"workflow_id"`
	TaskName     string      `json:"task_name"`
	TaskType     string      `json:"task_type"`
	Dependencies []byte      `json:"dependencies"`
	Priority     int32       `json:"priority"`
}
