// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	ClaimTask(ctx context.Context, arg ClaimTaskParams) (TaskExecution, error)
	CreateTaskExecution(ctx context.Context, arg CreateTaskExecutionParams) (TaskExecution, error)
	CreateTenant(ctx context.Context, name string) (Tenant, error)
	CreateWorkflow(ctx context.Context, arg CreateWorkflowParams) (Workflow, error)
	CreateWorkflowExecution(ctx context.Context, arg CreateWorkflowExecutionParams) (WorkflowExecution, error)
	CreateWorkflowTask(ctx context.Context, arg CreateWorkflowTaskParams) (WorkflowTask, error)
	GetPendingTasks(ctx context.Context, dollar_1 int32) ([]TaskExecution, error)
	GetWorker(ctx context.Context, id string) (Worker, error)
	GetWorkflow(ctx context.Context, id pgtype.UUID) (Workflow, error)
	GetWorkflowTasks(ctx context.Context, workflowID pgtype.UUID) ([]WorkflowTask, error)
	MarkStaleWorkersOffline(ctx context.Context, lastHeartbeat pgtype.Timestamptz) error
	RecordTaskAttempt(ctx context.Context, arg RecordTaskAttemptParams) (TaskAttempt, error)
	RegisterWorker(ctx context.Context, arg RegisterWorkerParams) (Worker, error)
	UpdateTaskExecutionStatus(ctx context.Context, arg UpdateTaskExecutionStatusParams) (TaskExecution, error)
	UpdateWorkerHeartbeat(ctx context.Context, arg UpdateWorkerHeartbeatParams) error
	UpdateWorkflowExecutionStatus(ctx context.Context, arg UpdateWorkflowExecutionStatusParams) (WorkflowExecution, error)
}

var _ Querier = (*Queries)(nil)
