// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: scheduler.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const failTaskExecution = `-- name: FailTaskExecution :one
UPDATE task_executions
SET status = 'FAILED',
    completed_at = CURRENT_TIMESTAMP,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, workflow_execution_id, workflow_task_id, status, worker_id, attempt, lease_expires_at, started_at, completed_at, created_at, updated_at, next_retry_at, max_attempts
`

func (q *Queries) FailTaskExecution(ctx context.Context, id pgtype.UUID) (TaskExecution, error) {
	row := q.db.QueryRow(ctx, failTaskExecution, id)
	var i TaskExecution
	err := row.Scan(
		&i.ID,
		&i.WorkflowExecutionID,
		&i.WorkflowTaskID,
		&i.Status,
		&i.WorkerID,
		&i.Attempt,
		&i.LeaseExpiresAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.NextRetryAt,
		&i.MaxAttempts,
	)
	return i, err
}

const markTaskForRetry = `-- name: MarkTaskForRetry :one
UPDATE task_executions
SET status = 'RETRY_WAIT',
    next_retry_at = $2,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, workflow_execution_id, workflow_task_id, status, worker_id, attempt, lease_expires_at, started_at, completed_at, created_at, updated_at, next_retry_at, max_attempts
`

type MarkTaskForRetryParams struct {
	ID          pgtype.UUID        `json:"id"`
	NextRetryAt pgtype.Timestamptz `json:"next_retry_at"`
}

func (q *Queries) MarkTaskForRetry(ctx context.Context, arg MarkTaskForRetryParams) (TaskExecution, error) {
	row := q.db.QueryRow(ctx, markTaskForRetry, arg.ID, arg.NextRetryAt)
	var i TaskExecution
	err := row.Scan(
		&i.ID,
		&i.WorkflowExecutionID,
		&i.WorkflowTaskID,
		&i.Status,
		&i.WorkerID,
		&i.Attempt,
		&i.LeaseExpiresAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.NextRetryAt,
		&i.MaxAttempts,
	)
	return i, err
}

const moveToDeadLetter = `-- name: MoveToDeadLetter :one
INSERT INTO dead_letter_tasks (task_execution_id, last_error)
VALUES ($1, $2)
RETURNING id, task_execution_id, last_error, created_at
`

type MoveToDeadLetterParams struct {
	TaskExecutionID pgtype.UUID `json:"task_execution_id"`
	LastError       pgtype.Text `json:"last_error"`
}

func (q *Queries) MoveToDeadLetter(ctx context.Context, arg MoveToDeadLetterParams) (DeadLetterTask, error) {
	row := q.db.QueryRow(ctx, moveToDeadLetter, arg.TaskExecutionID, arg.LastError)
	var i DeadLetterTask
	err := row.Scan(
		&i.ID,
		&i.TaskExecutionID,
		&i.LastError,
		&i.CreatedAt,
	)
	return i, err
}

const scheduleRetries = `-- name: ScheduleRetries :many
UPDATE task_executions
SET status = 'QUEUED',
    next_retry_at = NULL,
    updated_at = CURRENT_TIMESTAMP
WHERE status = 'RETRY_WAIT' AND next_retry_at <= CURRENT_TIMESTAMP
RETURNING id, workflow_execution_id, workflow_task_id, status, worker_id, attempt, lease_expires_at, started_at, completed_at, created_at, updated_at, next_retry_at, max_attempts
`

func (q *Queries) ScheduleRetries(ctx context.Context) ([]TaskExecution, error) {
	rows, err := q.db.Query(ctx, scheduleRetries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TaskExecution
	for rows.Next() {
		var i TaskExecution
		if err := rows.Scan(
			&i.ID,
			&i.WorkflowExecutionID,
			&i.WorkflowTaskID,
			&i.Status,
			&i.WorkerID,
			&i.Attempt,
			&i.LeaseExpiresAt,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.NextRetryAt,
			&i.MaxAttempts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
