// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: task.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimTask = `-- name: ClaimTask :one
UPDATE task_executions
SET status = 'ASSIGNED',
    worker_id = $1,
    lease_expires_at = $2,
    attempt = attempt + 1,
    updated_at = CURRENT_TIMESTAMP
WHERE id = (
    SELECT id FROM task_executions
    WHERE status = 'QUEUED' OR (status = 'ASSIGNED' AND lease_expires_at < CURRENT_TIMESTAMP)
    ORDER BY created_at ASC
    FOR UPDATE SKIP LOCKED
    LIMIT 1
)
RETURNING id, workflow_execution_id, workflow_task_id, status, worker_id, attempt, lease_expires_at, started_at, completed_at, created_at, updated_at, next_retry_at, max_attempts
`

type ClaimTaskParams struct {
	WorkerID       pgtype.Text        `json:"worker_id"`
	LeaseExpiresAt pgtype.Timestamptz `json:"lease_expires_at"`
}

func (q *Queries) ClaimTask(ctx context.Context, arg ClaimTaskParams) (TaskExecution, error) {
	row := q.db.QueryRow(ctx, claimTask, arg.WorkerID, arg.LeaseExpiresAt)
	var i TaskExecution
	err := row.Scan(
		&i.ID,
		&i.WorkflowExecutionID,
		&i.WorkflowTaskID,
		&i.Status,
		&i.WorkerID,
		&i.Attempt,
		&i.LeaseExpiresAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.NextRetryAt,
		&i.MaxAttempts,
	)
	return i, err
}

const createTaskExecution = `-- name: CreateTaskExecution :one
INSERT INTO task_executions (workflow_execution_id, workflow_task_id, status, attempt)
VALUES ($1, $2, 'PENDING', 0)
RETURNING id, workflow_execution_id, workflow_task_id, status, worker_id, attempt, lease_expires_at, started_at, completed_at, created_at, updated_at, next_retry_at, max_attempts
`

type CreateTaskExecutionParams struct {
	WorkflowExecutionID pgtype.UUID `json:"workflow_execution_id"`
	WorkflowTaskID      pgtype.UUID `json:"workflow_task_id"`
}

func (q *Queries) CreateTaskExecution(ctx context.Context, arg CreateTaskExecutionParams) (TaskExecution, error) {
	row := q.db.QueryRow(ctx, createTaskExecution, arg.WorkflowExecutionID, arg.WorkflowTaskID)
	var i TaskExecution
	err := row.Scan(
		&i.ID,
		&i.WorkflowExecutionID,
		&i.WorkflowTaskID,
		&i.Status,
		&i.WorkerID,
		&i.Attempt,
		&i.LeaseExpiresAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.NextRetryAt,
		&i.MaxAttempts,
	)
	return i, err
}

const getPendingTasks = `-- name: GetPendingTasks :many
SELECT id, workflow_execution_id, workflow_task_id, status, worker_id, attempt, lease_expires_at, started_at, completed_at, created_at, updated_at, next_retry_at, max_attempts FROM task_executions
WHERE status = 'PENDING'
ORDER BY created_at ASC
LIMIT $1::int
`

func (q *Queries) GetPendingTasks(ctx context.Context, dollar_1 int32) ([]TaskExecution, error) {
	rows, err := q.db.Query(ctx, getPendingTasks, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TaskExecution
	for rows.Next() {
		var i TaskExecution
		if err := rows.Scan(
			&i.ID,
			&i.WorkflowExecutionID,
			&i.WorkflowTaskID,
			&i.Status,
			&i.WorkerID,
			&i.Attempt,
			&i.LeaseExpiresAt,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.NextRetryAt,
			&i.MaxAttempts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordTaskAttempt = `-- name: RecordTaskAttempt :one
INSERT INTO task_attempts (task_execution_id, worker_id, attempt, status, error_message, completed_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, task_execution_id, worker_id, attempt, status, error_message, started_at, completed_at
`

type RecordTaskAttemptParams struct {
	TaskExecutionID pgtype.UUID        `json:"task_execution_id"`
	WorkerID        string             `json:"worker_id"`
	Attempt         int32              `json:"attempt"`
	Status          string             `json:"status"`
	ErrorMessage    pgtype.Text        `json:"error_message"`
	CompletedAt     pgtype.Timestamptz `json:"completed_at"`
}

func (q *Queries) RecordTaskAttempt(ctx context.Context, arg RecordTaskAttemptParams) (TaskAttempt, error) {
	row := q.db.QueryRow(ctx, recordTaskAttempt,
		arg.TaskExecutionID,
		arg.WorkerID,
		arg.Attempt,
		arg.Status,
		arg.ErrorMessage,
		arg.CompletedAt,
	)
	var i TaskAttempt
	err := row.Scan(
		&i.ID,
		&i.TaskExecutionID,
		&i.WorkerID,
		&i.Attempt,
		&i.Status,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const updateTaskExecutionStatus = `-- name: UpdateTaskExecutionStatus :one
UPDATE task_executions
SET status = $2,
    completed_at = $3,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, workflow_execution_id, workflow_task_id, status, worker_id, attempt, lease_expires_at, started_at, completed_at, created_at, updated_at, next_retry_at, max_attempts
`

type UpdateTaskExecutionStatusParams struct {
	ID          pgtype.UUID        `json:"id"`
	Status      string             `json:"status"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
}

func (q *Queries) UpdateTaskExecutionStatus(ctx context.Context, arg UpdateTaskExecutionStatusParams) (TaskExecution, error) {
	row := q.db.QueryRow(ctx, updateTaskExecutionStatus, arg.ID, arg.Status, arg.CompletedAt)
	var i TaskExecution
	err := row.Scan(
		&i.ID,
		&i.WorkflowExecutionID,
		&i.WorkflowTaskID,
		&i.Status,
		&i.WorkerID,
		&i.Attempt,
		&i.LeaseExpiresAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.NextRetryAt,
		&i.MaxAttempts,
	)
	return i, err
}
