// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: worker.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getWorker = `-- name: GetWorker :one
SELECT id, hostname, version, max_concurrent_tasks, active_tasks, supported_task_types, last_heartbeat, status, created_at, updated_at FROM workers
WHERE id = $1
`

func (q *Queries) GetWorker(ctx context.Context, id string) (Worker, error) {
	row := q.db.QueryRow(ctx, getWorker, id)
	var i Worker
	err := row.Scan(
		&i.ID,
		&i.Hostname,
		&i.Version,
		&i.MaxConcurrentTasks,
		&i.ActiveTasks,
		&i.SupportedTaskTypes,
		&i.LastHeartbeat,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markStaleWorkersOffline = `-- name: MarkStaleWorkersOffline :exec
UPDATE workers
SET status = 'OFFLINE',
    updated_at = CURRENT_TIMESTAMP
WHERE status = 'ONLINE' AND last_heartbeat < $1
`

func (q *Queries) MarkStaleWorkersOffline(ctx context.Context, lastHeartbeat pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, markStaleWorkersOffline, lastHeartbeat)
	return err
}

const registerWorker = `-- name: RegisterWorker :one
INSERT INTO workers (id, hostname, version, max_concurrent_tasks, active_tasks, supported_task_types, last_heartbeat, status)
VALUES ($1, $2, $3, $4, 0, $5, CURRENT_TIMESTAMP, 'ONLINE')
ON CONFLICT (id) DO UPDATE
SET hostname = EXCLUDED.hostname,
    version = EXCLUDED.version,
    max_concurrent_tasks = EXCLUDED.max_concurrent_tasks,
    supported_task_types = EXCLUDED.supported_task_types,
    last_heartbeat = CURRENT_TIMESTAMP,
    status = 'ONLINE',
    updated_at = CURRENT_TIMESTAMP
RETURNING id, hostname, version, max_concurrent_tasks, active_tasks, supported_task_types, last_heartbeat, status, created_at, updated_at
`

type RegisterWorkerParams struct {
	ID                 string      `json:"id"`
	Hostname           string      `json:"hostname"`
	Version            pgtype.Text `json:"version"`
	MaxConcurrentTasks int32       `json:"max_concurrent_tasks"`
	SupportedTaskTypes []byte      `json:"supported_task_types"`
}

func (q *Queries) RegisterWorker(ctx context.Context, arg RegisterWorkerParams) (Worker, error) {
	row := q.db.QueryRow(ctx, registerWorker,
		arg.ID,
		arg.Hostname,
		arg.Version,
		arg.MaxConcurrentTasks,
		arg.SupportedTaskTypes,
	)
	var i Worker
	err := row.Scan(
		&i.ID,
		&i.Hostname,
		&i.Version,
		&i.MaxConcurrentTasks,
		&i.ActiveTasks,
		&i.SupportedTaskTypes,
		&i.LastHeartbeat,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateWorkerHeartbeat = `-- name: UpdateWorkerHeartbeat :exec
UPDATE workers
SET active_tasks = $2,
    last_heartbeat = CURRENT_TIMESTAMP,
    status = 'ONLINE',
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
`

type UpdateWorkerHeartbeatParams struct {
	ID          string `json:"id"`
	ActiveTasks int32  `json:"active_tasks"`
}

func (q *Queries) UpdateWorkerHeartbeat(ctx context.Context, arg UpdateWorkerHeartbeatParams) error {
	_, err := q.db.Exec(ctx, updateWorkerHeartbeat, arg.ID, arg.ActiveTasks)
	return err
}
