// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workflow.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTenant = `-- name: CreateTenant :one
INSERT INTO tenants (name)
VALUES ($1)
RETURNING id, name, created_at, updated_at
`

func (q *Queries) CreateTenant(ctx context.Context, name string) (Tenant, error) {
	row := q.db.QueryRow(ctx, createTenant, name)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createWorkflow = `-- name: CreateWorkflow :one
INSERT INTO workflows (tenant_id, name, definition, version)
VALUES ($1, $2, $3, $4)
RETURNING id, tenant_id, name, definition, version, status, created_at, updated_at
`

type CreateWorkflowParams struct {
	TenantID   pgtype.UUID `json:"tenant_id"`
	Name       string      `json:"name"`
	Definition []byte      `json:"definition"`
	Version    int32       `json:"version"`
}

func (q *Queries) CreateWorkflow(ctx context.Context, arg CreateWorkflowParams) (Workflow, error) {
	row := q.db.QueryRow(ctx, createWorkflow,
		arg.TenantID,
		arg.Name,
		arg.Definition,
		arg.Version,
	)
	var i Workflow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Definition,
		&i.Version,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createWorkflowExecution = `-- name: CreateWorkflowExecution :one
INSERT INTO workflow_executions (tenant_id, workflow_id, idempotency_key, status)
VALUES ($1, $2, $3, 'PENDING')
RETURNING id, tenant_id, workflow_id, idempotency_key, status, started_at, completed_at, created_at, updated_at
`

type CreateWorkflowExecutionParams struct {
	TenantID       pgtype.UUID `json:"tenant_id"`
	WorkflowID     pgtype.UUID `json:"workflow_id"`
	IdempotencyKey pgtype.Text `json:"idempotency_key"`
}

func (q *Queries) CreateWorkflowExecution(ctx context.Context, arg CreateWorkflowExecutionParams) (WorkflowExecution, error) {
	row := q.db.QueryRow(ctx, createWorkflowExecution, arg.TenantID, arg.WorkflowID, arg.IdempotencyKey)
	var i WorkflowExecution
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.WorkflowID,
		&i.IdempotencyKey,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createWorkflowTask = `-- name: CreateWorkflowTask :one
INSERT INTO workflow_tasks (workflow_id, task_name, task_type, dependencies, priority)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, workflow_id, task_name, task_type, dependencies, priority
`

type CreateWorkflowTaskParams struct {
	WorkflowID   pgtype.UUID `json:"workflow_id"`
	TaskName     string      `json:"task_name"`
	TaskType     string      `json:"task_type"`
	Dependencies []byte      `json:"dependencies"`
	Priority     int32       `json:"priority"`
}

func (q *Queries) CreateWorkflowTask(ctx context.Context, arg CreateWorkflowTaskParams) (WorkflowTask, error) {
	row := q.db.QueryRow(ctx, createWorkflowTask,
		arg.WorkflowID,
		arg.TaskName,
		arg.TaskType,
		arg.Dependencies,
		arg.Priority,
	)
	var i WorkflowTask
	err := row.Scan(
		&i.ID,
		&i.WorkflowID,
		&i.TaskName,
		&i.TaskType,
		&i.Dependencies,
		&i.Priority,
	)
	return i, err
}

const getWorkflow = `-- name: GetWorkflow :one
SELECT id, tenant_id, name, definition, version, status, created_at, updated_at FROM workflows
WHERE id = $1
`

func (q *Queries) GetWorkflow(ctx context.Context, id pgtype.UUID) (Workflow, error) {
	row := q.db.QueryRow(ctx, getWorkflow, id)
	var i Workflow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Definition,
		&i.Version,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkflowTasks = `-- name: GetWorkflowTasks :many
SELECT id, workflow_id, task_name, task_type, dependencies, priority FROM workflow_tasks
WHERE workflow_id = $1
`

func (q *Queries) GetWorkflowTasks(ctx context.Context, workflowID pgtype.UUID) ([]WorkflowTask, error) {
	rows, err := q.db.Query(ctx, getWorkflowTasks, workflowID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkflowTask
	for rows.Next() {
		var i WorkflowTask
		if err := rows.Scan(
			&i.ID,
			&i.WorkflowID,
			&i.TaskName,
			&i.TaskType,
			&i.Dependencies,
			&i.Priority,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWorkflowExecutionStatus = `-- name: UpdateWorkflowExecutionStatus :one
UPDATE workflow_executions
SET status = $2, started_at = $3, completed_at = $4, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, tenant_id, workflow_id, idempotency_key, status, started_at, completed_at, created_at, updated_at
`

type UpdateWorkflowExecutionStatusParams struct {
	ID          pgtype.UUID        `json:"id"`
	Status      string             `json:"status"`
	StartedAt   pgtype.Timestamptz `json:"started_at"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
}

func (q *Queries) UpdateWorkflowExecutionStatus(ctx context.Context, arg UpdateWorkflowExecutionStatusParams) (WorkflowExecution, error) {
	row := q.db.QueryRow(ctx, updateWorkflowExecutionStatus,
		arg.ID,
		arg.Status,
		arg.StartedAt,
		arg.CompletedAt,
	)
	var i WorkflowExecution
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.WorkflowID,
		&i.IdempotencyKey,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
